name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          changelog: CHANGELOG.md
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: Initialization environment
        run: |
          yum install -y libpcap-devel
          set -euxo pipefail
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
          echo "$HOME/.cargo/bin" >>"${GITHUB_PATH}"
          yum install epel-release -y
          yum install jq dnf -y
          yum install centos-release-scl -y
          yum install devtoolset-11-gcc* -y
          echo "/opt/rh/devtoolset-11/root/bin" >>"${GITHUB_PATH}"
          dnf install 'dnf-command(config-manager)' -y
          dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          dnf install gh -y
          yum remove git
          yum install https://repo.ius.io/ius-release-el7.rpm
          yum install git236

      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: traffic-by-ip-exporter
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
